const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);let projects=[],active=null,poll;
async function api(path,options={}){const r=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},...options});if(!r.ok){const e=await r.json().catch(()=>({detail:r.statusText}));throw Error(e.detail)}return r.status===204?null:r.json()}
function toast(message){const e=$('#toast');e.textContent=message;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
async function loadProjects(preferred){projects=await api('/projects');active=projects.find(p=>p.id===(preferred||active?.id))||projects[0]||null;renderTabs();render();}
function renderTabs(){const nav=$('#tabs');nav.querySelectorAll('.project').forEach(e=>e.remove());projects.forEach(p=>{const b=document.createElement('button');b.className='project '+(p.id===active?.id?'active':'');b.textContent=(p.enabled?'● ':'○ ')+p.name;b.onclick=()=>{active=p;renderTabs();render()};nav.insertBefore(b,$('#addTab'))})}
async function render(){clearInterval(poll);$('#empty').hidden=!!active;$('#dashboard').hidden=!active;if(!active)return;$('#projectName').textContent=active.name;$('#projectUrl').textContent=active.frontend_url;$('#projectUrl').href=active.frontend_url;await loadRuns();poll=setInterval(loadRuns,2000)}
async function loadRuns(){if(!active)return;const runs=await api(`/projects/${active.id}/runs`);const box=$('#runs');if(!runs.length){box.innerHTML='<p class="muted">No runs recorded yet. Every result and artifact will appear here.</p>';return}box.innerHTML=runs.slice(0,20).map(r=>`<div class="run"><span class="badge ${r.status}">◆ ${r.status}</span><b>${r.suite.toUpperCase()}</b><span>${new Date(r.started_at).toLocaleString()} ${r.current_stage?'· '+r.current_stage:''}</span><span>${r.duration_ms==null?'…':(r.duration_ms/1000).toFixed(1)+'s'}</span></div>`).join('');const latest=runs[0];$('#overall').className='status '+latest.status;$('#overall b').textContent=latest.status;for(const cat of ['system','api','e2e','security']){const found=runs.find(r=>r.suite===cat||r.suite==='all');$('#'+cat+'Metric').textContent=found?found.status:'—'}if(runs.some(r=>['QUEUED','RUNNING'].includes(r.status)))return;clearInterval(poll)}
function openForm(edit=false){const f=$('#projectForm');f.reset();f.enabled.checked=true;$('#formError').textContent='';$('#deleteProject').hidden=!edit;$('#formTitle').textContent=edit?'Edit project':'Add project';if(edit&&active)for(const [k,v] of Object.entries(active)){if(f.elements[k]){if(k==='enabled')f.elements[k].checked=v;else f.elements[k].value=Array.isArray(v)?v.join(', '):(v??'')}}$('#projectDialog').showModal()}
$('#projectForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f));d.enabled=f.enabled.checked;d.expected_ports=d.expected_ports?d.expected_ports.split(',').map(Number):[];d.process_rules=d.process_rules?d.process_rules.split(',').map(x=>x.trim()).filter(Boolean):[];['backend_url','health_url','project_path'].forEach(k=>{if(!d[k])d[k]=null});try{const p=await api(d.id?`/projects/${d.id}`:'/projects',{method:d.id?'PUT':'POST',body:JSON.stringify(d)});$('#projectDialog').close();await loadProjects(p.id);toast('Project saved')}catch(err){$('#formError').textContent=err.message}};
$('#deleteProject').onclick=async()=>{if(active&&confirm(`Delete ${active.name} and its complete run history?`)){await api(`/projects/${active.id}`,{method:'DELETE'});$('#projectDialog').close();active=null;await loadProjects();toast('Project deleted')}};
$$('[data-close]').forEach(b=>b.onclick=()=>$('#projectDialog').close());$$('[data-add]').forEach(b=>b.onclick=()=>openForm());$('#addTab').onclick=()=>openForm();$('#editProject').onclick=()=>openForm(true);$('#refresh').onclick=loadRuns;
async function run(suite){if(!active)return;try{await api(`/projects/${active.id}/run/${suite}`,{method:'POST',body:'{}'});toast(`${suite.toUpperCase()} queued`);await loadRuns();poll=setInterval(loadRuns,1500)}catch(e){toast(e.message)}}
$$('[data-run]').forEach(b=>b.onclick=()=>run(b.dataset.run));$('#runAll').onclick=()=>run('all');setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString(),1000);loadProjects().catch(e=>toast(e.message));
